name: Publish Maven Artifacts

on:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions:
  contents: read

env:
  THIRD_PARTY_MAVEN_REPOSITORY_URL: https://${{ secrets.PENTAHO_CICD_ONE_USER }}:${{ secrets.PENTAHO_CICD_ONE_KEY }}@repo.pentaho.com/artifactory/pntpub-maven-3rdparty-release
  THIRD_PARTY_BUNDLE_WRAPS_REPOSITORY_URL: https://${{ secrets.PENTAHO_CICD_ONE_USER }}:${{ secrets.PENTAHO_CICD_ONE_KEY }}@repo.pentaho.com/artifactory/third-party-bundle-wraps

concurrency:
  group: publish-maven-artifacts
  cancel-in-progress: false

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: [k8s]

    container:
      image: ${{ vars.ARTIFACTORY_HOST }}/docker/jenkins-build/maven/open-jdk/17
      credentials:
        username: ${{ secrets.PENTAHO_CICD_ONE_USER }}
        password: ${{ secrets.PENTAHO_CICD_ONE_KEY }}
      volumes:
        - /home/runner/caches/pentaho/.m2:/root/.m2

    steps:
      - name: Checkout merged revision
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Retrieve Maven settings
        id: common-maven
        uses: pentaho/actions-common@stable

      - name: Configure Maven settings
        shell: sh
        run: cp "${{ steps.common-maven.outputs.settings-file-path }}" /root/.m2/settings.xml

      - name: Build and publish to third-party Maven repository
        run: >
          mvn --batch-mode --errors clean deploy
          -DaltDeploymentRepository=third-party-maven::default::${{ env.THIRD_PARTY_MAVEN_REPOSITORY_URL }}

      - name: Publish to third-party bundle wraps repository
        run: >
          mvn --batch-mode --errors deploy
          -DaltDeploymentRepository=third-party-bundle-wraps::default::${{ env.THIRD_PARTY_BUNDLE_WRAPS_REPOSITORY_URL }}
